apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: testns  # Ensure it deploys in the correct namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: errigiova/myapp:latest
          ports:
            - containerPort: 5000
